[platformio]
src_dir = examples
default_envs = weather-clock

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_SKIP
    -DLV_COLOR_DEPTH=16
    -DLV_USE_STDLIB_MALLOC=LV_STDLIB_CLIB
    -DLV_USE_STDLIB_STRING=LV_STDLIB_CLIB
    -DLV_USE_STDLIB_SPRINTF=LV_STDLIB_CLIB
    -DLV_FONT_MONTSERRAT_20=1
    -DLV_FONT_MONTSERRAT_28=1
    -DLV_FONT_MONTSERRAT_48=1
lib_deps =
    moononournation/GFX Library for Arduino@^1.5.6
    lvgl/lvgl@^9.2.2
    bblanchon/ArduinoJson@^7.2.0
    bitbank2/JPEGDEC@^1.7.0

[env:weather-clock]
build_src_filter = -<*> +<weather-clock/>

[env:lvgl-basic]
build_src_filter = -<*> +<lvgl-basic/>

[env:media-player]
build_src_filter = -<*> +<media-player/>

[env:music-player]
build_src_filter = -<*> +<music-player/>
build_flags =
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    ${env.lib_deps}
    https://github.com/schreibfaul1/ESP32-audioI2S.git

[env:paint]
build_src_filter = -<*> +<paint/>
